# Generated by Django 5.1.7 on 2025-04-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='service',
            new_name='description',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='hobbies',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
