# Generated by Django 5.1.6 on 2025-03-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='communication_preference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
