# Generated by Django 5.1.6 on 2025-02-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_group_field_of_study_alter_group_year_of_study_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='field_of_study',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
