# Generated by Django 5.1.7 on 2025-05-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hobby_alter_groupmembership_role_groupchat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hstudents',
            name='schoolName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hstudents',
            name='studyLevel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hstudents',
            name='subjects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
