# Generated by Django 5.1.7 on 2025-04-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_service_serviceprovider_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='piece_jobs',
            new_name='qualification',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='subject_expertise',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='phone_number',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
