# Generated by Django 5.1.7 on 2025-05-07 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hstudents_schoolname_hstudents_studylevel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='company_name',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='description',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='hobbies',
            new_name='sectors',
        ),
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='qualification',
            new_name='serviceNeeds',
        ),
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='typeofservice',
            new_name='usageType',
        ),
    ]
