# Generated by Django 5.1.7 on 2025-04-11 20:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking_booking_source_booking_current_participants_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutoravailability',
            options={'ordering': ['start_time']},
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='communication_preference',
            new_name='institution',
        ),
        migrations.AlterUniqueTogether(
            name='externalcalendarconnection',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='meetingprovider',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='calendlyevent',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='muted_until',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tutoravailability',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='availability',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingprovider',
            name='credentials',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='about',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(default='direct', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='calendly_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.calendlyevent'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='current_participants',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration_minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='max_participants',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='meeting_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendlyevent',
            name='calendly_event_uri',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='calendlyevent',
            name='cancellation_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='calendlyevent',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='calendlyevent',
            name='reschedule_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('tutor', 'Tutor'), ('student', 'Student'), ('hs student', 'HS Student'), ('service provider', 'Service Provider'), ('job seeker', 'Job Seeker')], default='student', max_length=50),
        ),
        migrations.AlterField(
            model_name='externalcalendarconnection',
            name='calendly_uri',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='externalcalendarconnection',
            name='calendly_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='externalcalendarconnection',
            name='provider',
            field=models.CharField(choices=[('google', 'Google Calendar'), ('outlook', 'Outlook Calendar'), ('calendly', 'Calendly'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='externalcalendarconnection',
            name='provider_user_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='externalcalendarconnection',
            name='token_expires_at',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='administered_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('study', 'Study Group'), ('hobby', 'Hobby Group')], max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='hobbies',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='invite_link',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='custom_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MODERATOR', 'Moderator'), ('MEMBER', 'Member')], default='MEMBER', max_length=10),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingprovider',
            name='provider',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('microsoft_teams', 'Microsoft Teams'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tutoravailability',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hstudent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('typeofservice', models.TextField()),
                ('qualification', models.TextField()),
                ('interests', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serviceprovider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='externalcalendarconnection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='externalcalendarconnection',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='meetingprovider',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='meetingprovider',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meetingprovider',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='meetingprovider',
            name='provider_user_id',
        ),
        migrations.RemoveField(
            model_name='meetingprovider',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='meetingprovider',
            name='token_expires_at',
        ),
        migrations.RemoveField(
            model_name='meetingprovider',
            name='updated_at',
        ),
    ]
