# Generated by Django 5.1.6 on 2025-02-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_group_field_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='year_of_study',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
