# Generated by Django 5.1.7 on 2025-05-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_interests_serviceprovider_hobbies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='about',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
