# Generated by Django 5.1.6 on 2025-02-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_group_field_of_study_alter_group_year_of_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='subject_specialization',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(related_name='tutors', to='myapp.subjectspecialization'),
        ),
    ]
